Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -1,4 +1,3 @@
-
 on:
   push:
     branches: [ main ]
@@ -13,251 +12,270 @@ on:
 
 jobs:
         
-  # snyk:
-    # name: snyk for vulns
-    # runs-on: ubuntu-latest
-    # steps:
-      # - name: Checkout
-        # uses: actions/checkout@v2
+  snyk:
+    name: snyk for vulns
+    env:
+      ACTION: Snyk scan
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
       
-      # - name: Run Snyk to check configuration files for security issues
-        # uses: snyk/actions/golang@master
-        # env:
-          # SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-        # with:
-          # args: --sarif-file-output=snyk.sarif        
-      # - name: Upload result to GitHub Code Scanning
-        # uses: github/codeql-action/upload-sarif@v1
-        # if: always()
-        # with:
-          # sarif_file: snyk.sarif
+      - name: Run Snyk to check configuration files for security issues
+        uses: snyk/actions/golang@master
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        with:
+          args: --sarif-file-output=snyk.sarif        
+      - name: Upload result to GitHub Code Scanning
+        uses: github/codeql-action/upload-sarif@v1
+        if: always()
+        with:
+          sarif_file: snyk.sarif
           
-      # - name: send massage to tg
-        # if: always()
-        # uses: appleboy/telegram-action@master
-        # with:
-          # to: ${{ secrets.TELEGRAM_TO }}
-          # token: ${{ secrets.TELEGRAM_TOKEN }}
-          # message: |
-            # ${{ github.actor }} created commit:
-            # Commit message: ${{ github.event.commits[0].message }}
-            # Repository: https://github.com/${{ github.repository }}/commit/${{github.sha}}
-            # Result: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
-          # #format: "markdown"
-          # disable_web_page_preview: true
+      - name: send massage to tg
+        if: always()
+        uses: appleboy/telegram-action@master
+        with:
+          to: ${{ secrets.TELEGRAM_TO }}
+          token: ${{ secrets.TELEGRAM_TOKEN }}
+          message: |
+            ${{ github.actor }} created commit:
+            *Commit message:* ${{ github.event.commits[0].message }}
+            *Repository:*  [${{ github.repository }}](https://github.com/${{ github.repository }}/commit/${{github.sha}}) 
+            *Result:* ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
+            *Action:* ${{ env.ACTION }}
+            *Status:* ${{ job.status }}
+          format: "markdown"
+          disable_web_page_preview: true
           
-      # # - name: Send Gmail notification
-        # # if: always()
-        # # uses: dawidd6/action-send-mail@v3
-        # # with:
-            # # server_address: smtp.yandex.ru
-            # # server_port: 465
-            # # username: ${{secrets.YANDEX_MAIL_USERNAME}}
-            # # password: ${{secrets.YANDEX_MAIL_PASSWORD}}
-            # # subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
-            # # to: ${{ secrets.MAIL_FOR_INFO }}
-            # # from: github action ${{github.sha}} on ${{github.repository}}
-            # # body: Build job of ${{github.repository}} completed successfully!
-            # # attachments: snyk.sarif
-  # tests:
-    # needs: snyk
-    # name: testing and building
-    # runs-on: ubuntu-latest
-    # steps:
-    # - uses: actions/checkout@v2
-    # - name: install go 
-      # uses: actions/setup-go@v2
-      # with:
-        # go-version: 1.15.15
-    # - name: building
-      # run: go build -v ./...
-    # - name: testing
-      # run: go test -v ./...
-    # - name: send massage to tg
+      # - name: Send Gmail notification
+        # if: always()
+        # uses: dawidd6/action-send-mail@v3
+        # with:
+            # server_address: smtp.yandex.ru
+            # server_port: 465
+            # username: ${{secrets.YANDEX_MAIL_USERNAME}}
+            # password: ${{secrets.YANDEX_MAIL_PASSWORD}}
+            # subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
+            # to: ${{ secrets.MAIL_FOR_INFO }}
+            # from: github action ${{github.sha}} on ${{github.repository}}
+            # body: Build job of ${{github.repository}} completed successfully!
+            # attachments: snyk.sarif
+  tests:
+    needs: snyk
+    name: testing and building
+    env:
+      ACTION: Golang self test and build
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v2
+    - name: install go 
+      uses: actions/setup-go@v2
+      with:
+        go-version: 1.15.15
+    - name: building
+      run: go build -v ./...
+    - name: testing
+      run: go test -v ./...
+    - name: send massage to tg
+      if: always()
+      uses: appleboy/telegram-action@master
+      with:
+          to: ${{ secrets.TELEGRAM_TO }}
+          token: ${{ secrets.TELEGRAM_TOKEN }}
+          message: |
+            ${{ github.actor }} created commit:
+            *Commit message:* ${{ github.event.commits[0].message }}
+            *Repository:*  [${{ github.repository }}](https://github.com/${{ github.repository }}/commit/${{github.sha}}) 
+            *Result:* ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
+            *Action:* ${{ env.ACTION }}
+            *Status:* ${{ job.status }}
+          format: "markdown"
+          disable_web_page_preview: true
+          
+    # - name: Send Gmail notification
       # if: always()
-      # uses: appleboy/telegram-action@master
+      # uses: dawidd6/action-send-mail@v3
       # with:
-          # to: ${{ secrets.TELEGRAM_TO }}
-          # token: ${{ secrets.TELEGRAM_TOKEN }}
-          # message: |
-            # ${{ github.actor }} created commit:
-            # Commit message: ${{ github.event.commits[0].message }}
-            # Repository: https://github.com/${{ github.repository }}/commit/${{github.sha}}
-            # Result: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
-          # #format: "markdown"
-          # disable_web_page_preview: true
-          
-    # # - name: Send Gmail notification
-      # # if: always()
-      # # uses: dawidd6/action-send-mail@v3
-      # # with:
-            # # server_address: smtp.yandex.ru
-            # # server_port: 465
-            # # username: ${{secrets.YANDEX_MAIL_USERNAME}}
-            # # password: ${{secrets.YANDEX_MAIL_PASSWORD}}
-            # # subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
-            # # to: ${{ secrets.MAIL_FOR_INFO }}
-            # # from: github action ${{github.sha}} on ${{github.repository}}
-            # # body: test job of ${{github.repository}} completed successfully!
-            # # attachments: snyk.sarif  
-  # golangci:
-    # needs: tests
-    # name: lint
-    # runs-on: ubuntu-latest
-    # steps:
-      # - uses: actions/checkout@v2
-      # - name: golangci-lint
-        # uses: golangci/golangci-lint-action@v2
-        # with:
-          # # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
-          # version: latest
+            # server_address: smtp.yandex.ru
+            # server_port: 465
+            # username: ${{secrets.YANDEX_MAIL_USERNAME}}
+            # password: ${{secrets.YANDEX_MAIL_PASSWORD}}
+            # subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
+            # to: ${{ secrets.MAIL_FOR_INFO }}
+            # from: github action ${{github.sha}} on ${{github.repository}}
+            # body: test job of ${{github.repository}} completed successfully!
+            # attachments: snyk.sarif  
+  golangci:
+    needs: tests
+    name: lint
+    env:
+      ACTION: Linter test
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - name: golangci-lint
+        uses: golangci/golangci-lint-action@v2
+        with:
+          version: latest
 
             
-################## HERE CAN BE GOSEC CHECK ####################        
+################# HERE CAN BE GOSEC CHECK ####################        
   
-  # deployecr:
-    # name: deploying aws ecr with terraform
-    # runs-on: ubuntu-latest
-    # defaults:
-      # run:
-        # working-directory: awsecr
-   # # needs: golangci
-    # env:
-      # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
-      # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
-      # AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
+  deployecr:
+    name: deploying aws ecr with terraform
+    env:
+      ACTION: Deploy ECR storage with Terraform
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: awsecr
+    needs: golangci
+    env:
+      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
+      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  
-    # steps:
-      # - name: Checkout 
-        # uses: actions/checkout@v2
+    steps:
+      - name: Checkout 
+        uses: actions/checkout@v2
 
-      # - name: Setup Terraform
-        # uses: hashicorp/setup-terraform@v1
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v1
 
-      # - name: Terraform format
-        # run: terraform fmt -check
-        # continue-on-error: true
+      - name: Terraform format
+        run: terraform fmt -check
+        continue-on-error: true
 
-      # - name: Terraform init
-        # run: terraform init
+      - name: Terraform init
+        run: terraform init
       
-      # - name: Terraform validate
-        # run: terraform validate
-        # continue-on-error: true
+      - name: Terraform validate
+        run: terraform validate
+        continue-on-error: true
 
-      # - name: Terraform plan
-        # id: plan
-        # run: terraform plan
-        # continue-on-error: true
+      - name: Terraform plan
+        id: plan
+        run: terraform plan
+        continue-on-error: true
 
-      # - name: Terraform Apply
-        # run: terraform apply -auto-approve
-        # continue-on-error: true
+      - name: Terraform Apply
+        run: terraform apply -auto-approve
+        continue-on-error: true
         
-      # - name: send massage to tg
+      - name: send massage to tg
+        if: always()
+        uses: appleboy/telegram-action@master
+        with:
+          to: ${{ secrets.TELEGRAM_TO }}
+          token: ${{ secrets.TELEGRAM_TOKEN }}
+          message: |
+            ${{ github.actor }} created commit:
+            *Commit message:* ${{ github.event.commits[0].message }}
+            *Repository:*  [${{ github.repository }}](https://github.com/${{ github.repository }}/commit/${{github.sha}}) 
+            *Result:* ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
+            *Action:* ${{ env.ACTION }}
+            *Status:* ${{ job.status }}
+          format: "markdown"
+          disable_web_page_preview: true
+        
+      # - name: Send Gmail notification
         # if: always()
-        # uses: appleboy/telegram-action@master
+        # uses: dawidd6/action-send-mail@v3
         # with:
-          # to: ${{ secrets.TELEGRAM_TO }}
-          # token: ${{ secrets.TELEGRAM_TOKEN }}
-          # message: |
-            # ${{ github.actor }} created commit:
-            # Commit message: ${{ github.event.commits[0].message }}
-            # Repository: https://github.com/${{ github.repository }}/commit/${{github.sha}}
-            # Result: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
-          # #format: "markdown"
-          # disable_web_page_preview: true  
+            # server_address: smtp.yandex.ru
+            # server_port: 465
+            # username: ${{secrets.YANDEX_MAIL_USERNAME}}
+            # password: ${{secrets.YANDEX_MAIL_PASSWORD}}
+            # subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
+            # to: ${{ secrets.MAIL_FOR_INFO }}
+            # from: github action ${{github.sha}} on ${{github.repository}}
+            # body: test job of ${{github.repository}} completed successfully!
         
-      # # - name: Send Gmail notification
-        # # if: always()
-        # # uses: dawidd6/action-send-mail@v3
-        # # with:
-            # # server_address: smtp.yandex.ru
-            # # server_port: 465
-            # # username: ${{secrets.YANDEX_MAIL_USERNAME}}
-            # # password: ${{secrets.YANDEX_MAIL_PASSWORD}}
-            # # subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
-            # # to: ${{ secrets.MAIL_FOR_INFO }}
-            # # from: github action ${{github.sha}} on ${{github.repository}}
-            # # body: test job of ${{github.repository}} completed successfully!
-        
-  # deployaws:
-    # name: deploying aws with terraform 
-    # runs-on: ubuntu-latest
-    # defaults:
-      # run:
-        # working-directory: awsdeploy
-    # # needs: deployecr
-    # env:
-      # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
-      # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
-      # AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
+  deployaws:
+    name: deploying aws with terraform 
+    runs-on: ubuntu-latest
+    env:
+      ACTION: Deploy AWS infrastructure with Terraform
+    defaults:
+      run:
+        working-directory: awsdeploy
+    needs: deployecr
+    env:
+      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
+      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  
-    # steps:
-      # - name: Checkout 
-        # uses: actions/checkout@v2
+    steps:
+      - name: Checkout 
+        uses: actions/checkout@v2
 
-      # - name: Setup Terraform
-        # uses: hashicorp/setup-terraform@v1
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v1
 
-      # - name: Terraform format
-        # run: terraform fmt -check
-        # continue-on-error: true
+      - name: Terraform format
+        run: terraform fmt -check
+        continue-on-error: true
 
-      # - name: Terraform init
-        # run: terraform init
+      - name: Terraform init
+        run: terraform init
         
-      # # - name: Download task definition
-        # # run: |
-            # # aws ecs describe-task-definition --task-definition definitiontaskgobridge --query taskDefinition > task-definition.json
-            # # ls -la
-     # # - name: Terraform taint
-     # #   run: terraform taint
+      # - name: Download task definition
+        # run: |
+            # aws ecs describe-task-definition --task-definition definitiontaskgobridge --query taskDefinition > task-definition.json
+            # ls -la
+     # - name: Terraform taint
+     #   run: terraform taint
       
-      # - name: Terraform validate
-        # run: terraform validate
+      - name: Terraform validate
+        run: terraform validate
 
-      # - name: Terraform plan
-        # id: plan
-        # run: terraform plan
-        # continue-on-error: true
+      - name: Terraform plan
+        id: plan
+        run: terraform plan
+        continue-on-error: true
 
-      # # - name: Terraform Plan Status
-        # # if: steps.plan.outcome == 'failure'
-        # # run: exit 1
+      # - name: Terraform Plan Status
+        # if: steps.plan.outcome == 'failure'
+        # run: exit 1
 
-      # - name: Terraform Apply
-        # run: terraform apply -auto-approve
+      - name: Terraform Apply
+        run: terraform apply -auto-approve
         
-      # - name: send massage to tg
+      - name: send massage to tg
+        if: always()
+        uses: appleboy/telegram-action@master
+        with:
+          to: ${{ secrets.TELEGRAM_TO }}
+          token: ${{ secrets.TELEGRAM_TOKEN }}
+          message: |
+            ${{ github.actor }} created commit:
+            *Commit message:* ${{ github.event.commits[0].message }}
+            *Repository:*  [${{ github.repository }}](https://github.com/${{ github.repository }}/commit/${{github.sha}}) 
+            *Result:* ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
+            *Action:* ${{ env.ACTION }}
+            *Status:* ${{ job.status }}
+          format: "markdown"
+          disable_web_page_preview: true  
+        
+      # - name: Send Gmail notification
         # if: always()
-        # uses: appleboy/telegram-action@master
+        # uses: dawidd6/action-send-mail@v3
         # with:
-          # to: ${{ secrets.TELEGRAM_TO }}
-          # token: ${{ secrets.TELEGRAM_TOKEN }}
-          # message: |
-            # ${{ github.actor }} created commit:
-            # Commit message: ${{ github.event.commits[0].message }}
-            # Repository: https://github.com/${{ github.repository }}/commit/${{github.sha}}
-            # Result: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
-          # #format: "markdown"
-          # disable_web_page_preview: true  
-        
-      # # - name: Send Gmail notification
-        # # if: always()
-        # # uses: dawidd6/action-send-mail@v3
-        # # with:
-            # # server_address: smtp.yandex.ru
-            # # server_port: 465
-            # # username: ${{secrets.YANDEX_MAIL_USERNAME}}
-            # # password: ${{secrets.YANDEX_MAIL_PASSWORD}}
-            # # subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
-            # # to: ${{ secrets.MAIL_FOR_INFO }}
-            # # from: github action ${{github.sha}} on ${{github.repository}}
-            # # body: test job of ${{github.repository}} completed successfully!
+            # server_address: smtp.yandex.ru
+            # server_port: 465
+            # username: ${{secrets.YANDEX_MAIL_USERNAME}}
+            # password: ${{secrets.YANDEX_MAIL_PASSWORD}}
+            # subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
+            # to: ${{ secrets.MAIL_FOR_INFO }}
+            # from: github action ${{github.sha}} on ${{github.repository}}
+            # body: test job of ${{github.repository}} completed successfully!
 
   pushtoecr:
-    # needs: deployaws
+    needs: deployaws
+    env:
+      ACTION: Push image to AWS ECS and update tasks in cluster
     name: start deploying to awc ecr
     runs-on: ubuntu-latest
     steps:
@@ -314,10 +332,12 @@ jobs:
           token: ${{ secrets.TELEGRAM_TOKEN }}
           message: |
             ${{ github.actor }} created commit:
-            Commit message: ${{ github.event.commits[0].message }}
-            Repository: https://github.com/${{ github.repository }}/commit/${{github.sha}}
-            Result: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
-          #format: "markdown"
+            *Commit message:* ${{ github.event.commits[0].message }}
+            *Repository:*  [${{ github.repository }}](https://github.com/${{ github.repository }}/commit/${{github.sha}}) 
+            *Result:* ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
+            *Action:* ${{ env.ACTION }}
+            *Status:* ${{ job.status }}
+          format: "markdown"
           disable_web_page_preview: true    
         
     # - name: Send Gmail notification
